### ISSUE TITLE
[bug] `yarn create tauri-app` not working if you have spaces in username

### ISSUE THREAD

**Issue by simonflick** [tauri-apps/create-tauri-app#1]
### Describe the bug

Running the command produced the following output:
```
PS C:\js> yarn create tauri-app
yarn create v1.22.17
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...

success Installed "create-tauri-app@1.0.0-rc.2" with binaries:
      - create-tauri-app
Der Befehl "C:\Users\Simon" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.
error Command failed.
Exit code: 1
Command: C:\Users\Simon Flick\AppData\Local\Yarn\bin\create-tauri-app
Arguments:
Directory: C:\js
Output:

info Visit https://yarnpkg.com/en/docs/cli/create for documentation about this command.
```

It worked when I ran the command manually and escaped my username:
`C:\Users\"Simon Flick"\AppData\Local\Yarn\bin\create-tauri-app`

### Platform and versions

```shell
Windows 10
```

**Comment by amrbashir** [comment]
What's the reason to have spaces? it is generally discouraged.

**Comment by simonflick** [comment]
> What's the reason to have spaces? it is generally discouraged.

I can't remember if I did that or if it came from setting up Windows with my Microsoft account. Anyways, spaces are a very natural thing to use and they are used by operating systems too (`C:\Program Files` and `~/Library/Application Support`). Not supporting them is a thing of the past that we should try to overcome.

**Comment by amrbashir** [comment]
Sorry, I thought you were using a name with spaces for the project name. 

Anyways, this seems like it might be a yarn problem, can you try `yarn create react-app` and see if it succeeds?

**Comment by simonflick** [comment]
You were right, it fails for the same reason. I also found this yarn bug report: [https://github.com/yarnpkg/yarn/issues/6851](https://github.com/yarnpkg/yarn/issues/6851)
