### ISSUE TITLE
Add @tauri-apps/cli to devDependencies

### ISSUE THREAD

**Issue by SheetJSDev** [tauri-apps/create-tauri-app#114]
Starting from scratch (options listed below):

```bash
$ npm create tauri-app
# ? What is your app name? SheetJSTauri
# ? What should the window title be? SheetJS + Tauri
# ? What UI recipe would you like to add? create-vite 
# ? Add "@tauri-apps/api" npm package? Yes
# ? Which vite template would you like to use? vue-ts
# ...
$ cd SheetJSTauri
$ npm run tauri
```

This prints some output.

Now try installing a module:

```bash
$ npm i --save https://cdn.sheetjs.com/xlsx-latest/xlsx-latest.tgz
$ npm run tauri

> SheetJSTauri@0.0.0 tauri
> tauri

sh: tauri: command not found
```

This happens because `npm` thinks the CLI tool is extraneous and wipes it when you try to install a dependency, **even if you choose to add `@tauri-apps/api`**.  If you start from scratch and run `npm ls`, you can clearly see the state:

```bash
$ npm ls
SheetJSTauri@0.0.0 /private/tmp/SheetJSTauri
├── @tauri-apps/cli-darwin-x64@1.0.5 extraneous
├── @tauri-apps/cli@1.0.5 extraneous
```

The fix is for the scaffold to add `@tauri-apps/cli` in `devDependencies`

**Comment by amrbashir** [comment]
`@tauri-apps/cli` is added to the `devDependencies` here https://github.com/tauri-apps/create-tauri-app/blob/e17dc70c319b0558f8be98e738f30ad76a5d2152/src/index.ts#L319-L322

I don't know why this happened to you but you could try the new templates from #90
