### ISSUE TITLE
Typo in all fragments

### ISSUE THREAD

**Issue by gBasil** [tauri-apps/create-tauri-app#140]
https://github.com/tauri-apps/create-tauri-app/search?q=developemnt
<img width="744" alt="image" src="https://user-images.githubusercontent.com/57513430/186794799-4a863b33-edac-4ecc-a534-7715a59f344a.png">

I would've created a PR, but I'd prefer not to wrangle GPG to work. Thank you for your time!

**Comment by amrbashir** [comment]
Thank you for the report, I will fix it soon.

**Comment by amrbashir** [comment]
fixed in #139, thanks again
