### ISSUE TITLE
Missing icon.icns in template

### ISSUE THREAD

**Issue by olivierlemasle** [tauri-apps/create-tauri-app#143]
When building an unmodified project generated using `create-tauri-app`, it fails with:

```
Error failed to bundle project: Failed to build data folders and files:
Failed to build data folders and files: Failed to create icon files:
Failed to create icon files: path matching icons/icon.icns not found.:
path matching icons/icon.icns not found.
error Command failed with exit code 1.
```

That's because the default `src-tauri/tauri.conf.json` includes

```
      "icon": [
        "icons/32x32.png",
        "icons/128x128.png",
        "icons/128x128@2x.png",
        "icons/icon.icns",
        "icons/icon.ico"
      ]
```

and `icon.icns` is not in the [list of currently provided icons](https://github.com/tauri-apps/create-tauri-app/tree/create-tauri-app-js-v2.1.0/packages/cli/fragments/base/src-tauri/icons).

Is it on purpose, e.g. because the [`icon.icns` file included in tauri](https://github.com/tauri-apps/tauri/blob/v1.0.5/tooling/cli/templates/app/src-tauri/icons/icon.icns) is pretty large (1.17 MB)?

Anyway, I think we should use one of these options:
1. Include the [`icon.icns` file included in tauri](https://github.com/tauri-apps/tauri/blob/v1.0.5/tooling/cli/templates/app/src-tauri/icons/icon.icns) (1.17 MB)
2. Or include a lighter `icon.icns` file
3. Or remove `icon.icns` from default `src-tauri/tauri.conf.json`.

What do you prefer?

**Comment by lucasfernog** [comment]
I think with the move of tauricon to the tauri CLI we could also generate the icons on init.

**Comment by lucasfernog** [comment]
Yeah we removed it from the template because it's too big.

**Comment by FabianLars** [comment]
I think something went wrong when it was exported (no idea how it was created in the first place), but it should be more around 300-400kb. So in case we don't want to generate it on init, ~350kb should be small enough to include maybe?

~~i guess once we re-introduce svg support, generating it on init would actually be pretty much perfect (no png resizing weirdness), _unless_ svg to png is really slow lol~~
Ah actually this would make CTA more complicated and much slower :/

**Comment by olivierlemasle** [comment]
> I think something went wrong when it was exported (no idea how it was created in the first place), but it should be more around 300-400kb.

`icon.icns` was updated (and grew larger) with https://github.com/tauri-apps/tauri/commit/72700ec, by @lorenzolewis

**Comment by FabianLars** [comment]
yes i saw that too, but it was already way too big before that (920kb) 🤷

**Comment by amrbashir** [comment]
I am okay with including it back again if it is only `300kb`, otherwise I will just remove it from `tauri.conf.json`

**Comment by olivierlemasle** [comment]
When generating the icons with `@tauri-apps/tauricon` from [app-icon.png](https://github.com/tauri-apps/tauri/blob/d88de300762063f15e140589e3dcaf37ce86e4f7/app-icon.png), I get a `icon.icns` which is only **`97kb`**. I can make a PR with this file added.

However, why this difference of size? I don't really know the `.icns` format (Apple Icon Image), and I don't own any Apple device, so I'm not sure the generated icon is actually good :man_shrugging:

**Comment by lorenzolewis** [comment]
@olivierlemasle can you include the generated `.icns` file? I know the `tauricon` repo is up next to get refactored so I'm not too familiar with the current format. My hunch is it's only bundling one size in the `.icns` format.

**Comment by FabianLars** [comment]
> However, why this difference of size?

Because the old tauricon icns generator is broken x) The main problem is that it uses a different bit depth than required by apple (it still seems to work in the resulting apps, but it's still not following the requirements)

This is the output of the new tauricon using icon.png from the tooling/cli template. It's less than 300kb now (240kb), no idea why actually since it was bigger when i created the PR, but anywayyy.
Anyway, someone with a mac needs to confirm that it's correct and works, no idea how tbh.
[icon.zip](https://github.com/tauri-apps/create-tauri-app/files/9440470/icon.zip)
(had to zip it because github doesn't like icns)

**Comment by lorenzolewis** [comment]
I just ran and bundled a test app with this icon @FabianLars and it works. Maybe something like this could blend in a bit more on the platform? Or the current gradient one that we have in the main repo, but was it the gradient that was causing the file size to increase? 

![app-icon-512@2x](https://user-images.githubusercontent.com/15347255/187095837-a67f65a7-c5c7-45da-b573-a5f5df23845d.png)

**Comment by FabianLars** [comment]
> but was it the gradient that was causing the file size to increase?

idk i used _whatever_ png file from an older dummy project i had on disk.

> Or the current gradient one that we have in the main repo

The gradient one is only in the .icns file and these are basically unusable on non-macos systems so i wasn't able to extract a png out of that (and was too lazy to do that via code...)
