### ISSUE TITLE
[Angular CLI] Reintroduce Angular CLI UI Recipe

### ISSUE THREAD

**Issue by BeMacized** [tauri-apps/create-tauri-app#166]
In v1 of `create-tauri-app`, there used to be a UI recipe for generating an Angular project, which was quite useful. 
v2 however does not seem to have it anymore.

I would love to see it come back!

**Comment by eneajaho** [comment]
I just made a pull request to add an Angular CLI template: https://github.com/tauri-apps/create-tauri-app/pull/167

**Comment by lorenzolewis** [comment]
Closing as it's now been added in release of 2.4 https://github.com/tauri-apps/create-tauri-app/releases/tag/create-tauri-app-v2.4.0 (thanks a bunch @eneajaho !)
