### ISSUE TITLE
Show `cargo install tauri-cli` before suggest `cargo tauri dev`

### ISSUE THREAD

**Issue by kuboon** [tauri-apps/create-tauri-app#177]
I've followed [Quick Start](https://tauri.app/v1/guides/getting-started/setup/) then saw message

```
Done, Now run:
  cd my-app
  cargo tauri dev
```

but it did not work because `tauri-cli` is not installed yet.

**Comment by kuboon** [comment]
Or it would be better if `create-tauri-app` automatically installs `tauri-cli`.

**Comment by amrbashir** [comment]
was that the vanilla template? I added a note tto install tauri-cli when using yew but orobably forgot vanilla
