### ISSUE TITLE
Update templates to Tauri 1.1

### ISSUE THREAD

**Issue by lorenzolewis** [tauri-apps/create-tauri-app#179]

**Comment by amrbashir** [comment]
no, I refuse

**Comment by FabianLars** [comment]
![shrek-pitchfork](https://user-images.githubusercontent.com/30730186/190524121-896b08b1-7648-4d62-9933-9d5bfca4ae4a.gif)

**Comment by amrbashir** [comment]
![RyanReynoldsUghGIF](https://user-images.githubusercontent.com/48618675/190525662-ac52210a-de15-40f6-9985-3157fd2e3bc0.gif)
