### ISSUE TITLE
Include additional steps for yew template

### ISSUE THREAD

**Issue by RyanBreaker** [tauri-apps/create-tauri-app#181]
When using CTA with the yew template, a couple additional steps are missing from the post-setup instructions. Currently, it gives the following output:

```
Done, Now run:
  cd a
  cargo tauri dev
```

Suggested change to include yew's [documented prerequisite](https://yew.rs/docs/tutorial#prerequisites) steps:

```
Done, Now run:
  cd a
  cargo install trunk
  rustup target add wasm32-unknown-unknown
  cargo tauri dev
```

Or, a note to complete those steps if not already done or a link can be included to the aforementioned prerequisites steps.

This would be beneficial to prevent confusion with new users.

**Comment by amrbashir** [comment]
there is a note before `Done, Now run:` that says
```
Please follow https://tauri.app/v1/guides/getting-started/prerequisites to install the needed prerequisites, if you haven't already.
You also need to install tauri-cli (cargo install tauri-cli) and trunk (https://trunkrs.dev/#install)
```

**Comment by RyanBreaker** [comment]
Oh my mistake, my terminal font color was hiding that message now that I looked.
