### ISSUE TITLE
Not working with yarn classic

### ISSUE THREAD

**Issue by bartoszkrawczyk2** [tauri-apps/create-tauri-app#192]
Hi, I'm getting an error:
```
Error failed to get project out directory: failed to get cargo metadata: No such file or directory (os error 2)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Steps to reproduce - just run
```
yarn create tauri-app
  select react-ts
yarn
yarn tauri dev
```

Is there any step required that is not mentioned in the docs?

My versions:
* node v16.17.1
* yarn 1.22.19
* MacOS 11.6

**Comment by FabianLars** [comment]
Sounds like you didn't [install Rust](https://tauri.app/v1/guides/getting-started/prerequisites#setting-up-macos) or didn't restart the terminal for it to take effect.

**Comment by bartoszkrawczyk2** [comment]
Yeah, restarting terminal helped. Silly issue. Thanks for the help!
