### ISSUE TITLE
[bug] "npm create tauri-app" fails on openSUSE Tumbleweed with "Not a directory" error

### ISSUE THREAD

**Issue by ancwrd1** [tauri-apps/create-tauri-app#193]
### Describe the bug

Trying to create a project under openSUSE Tumbleweed with `npm create tauri-app`, it fails with the following error:

```text
error: Not a directory (os error 20)
npm ERR! code 1
npm ERR! path /tmp
npm ERR! command failed
npm ERR! command sh -c -- create-tauri-app

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/x/.npm/_logs/2022-09-28T16_53_00_647Z-debug-0.log
```

Same error with any other tool (e.g. yarn).

### Platform and versions

```
Environment
  › OS: openSUSE 20220926 X64
  › Node.js: 18.9.1
  › npm: 8.19.1
  › pnpm: Not installed!
  › yarn: 1.22.19
  › rustup: 1.25.1
  › rustc: 1.64.0
  › cargo: 1.64.0
  › Rust toolchain: stable-x86_64-unknown-linux-gnu 
```

### Additional context

I tried running it with `strace` utility and the syscall which fails is:

`openat(AT_FDCWD, "/usr/bin/node18", O_RDONLY|O_NONBLOCK|O_CLOEXEC|O_DIRECTORY) = -1 ENOTDIR (Not a directory)`

Node.js installation contains two executables: `/usr/bin/node` (which seems to be a stub) and `/usr/bin/node18` (the real one).
If I rename `/usr/bin/node18` to `/usr/bin/node` then everything works.

This issue is specific to tauri, I tried for example creating other apps like react and it worked.

**Comment by amrbashir** [comment]
can you upload the full log here?

**Comment by ancwrd1** [comment]
Sure but I think it's not very helpful. Here is it:
[2022-09-28T16_53_00_647Z-debug-0.log](https://github.com/tauri-apps/create-tauri-app/files/9667786/2022-09-28T16_53_00_647Z-debug-0.log)

**Comment by ancwrd1** [comment]
Might be an issue with this line in the `create-tauri-app.js`:

```javascript
if (binStem === "node" || binStem === "nodejs") {
   ...
}
```

**Comment by amrbashir** [comment]
the logs shows that it fails to invoke create-tauri-app, can you try running inside a directory that isn't `/tmp` preferably `$HOME`

> Might be an issue with this line in the `create-tauri-app.js`:
> 
> ```js
> if (binStem === "node" || binStem === "nodejs") {
>    ...
> }
> ```

Nah this is just used to provide a better name for the cli in the help message

**Comment by ancwrd1** [comment]
I tried that already, the current directory doesn't really matter.
The difference is the nodejs executable name, if it's `/usr/bin/node` it works, if it's `/usr/bin/node18` (invoked by `/usr/bin/node`) then there is this "not a directory" error.

**Comment by amrbashir** [comment]
are you using any node manager like `nvm` or `fnm`?

**Comment by ancwrd1** [comment]
No, just installed node.js from the Linux repositories.

But it uses `libalternatives` method to launch a specific node version, so I can have version 18 and 17 installed at the same time.

The `/usr/bin/node` stub reads /usr/share/libalternatives/node/18.conf file which looks like:
```text
binary=/usr/bin/node18
man=node18.1
```
Then it execs this binary replacing itself (execve call).

**Comment by ancwrd1** [comment]
It's actually pretty simple to reproduce under Linux:
* Rename `/usr/bin/node` to `/usr/bin/node18`
* Create `/usr/bin/node` shell script with the following context:
```bash
#!/bin/bash
exec /usr/bin/node18 "$@"
```
* Mark it as executable with `chmod +x /usr/bin/node`

**Comment by amrbashir** [comment]
based on your last reproduction comment, I have this output:
```diff
amr - ~ took 4s 
❯ yarn create tauri-app
yarn create v1.22.17
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...

success Installed "create-tauri-app@2.5.0" with binaries:
      - create-tauri-app
[####] 4/4
+✔ Package name · usrbinnode185
error: Not a directory (os error 20)
error Command failed.
Exit code: 1
Command: /home/amr/.yarn/bin/create-tauri-app
Arguments: 
Directory: /home/amr
Output:

info Visit https://yarnpkg.com/en/docs/cli/create for documentation about this command.

amr - ~ took 23s 
❯                      
```

You can see the highlighting comment is asking for `Package name` pre-filled with `userbinnode18`. this step only happens when a path has been provided to the cli.

So somehow the cli is invoked like this `create-tauri-app /usr/bin/node18` so create-tauri-app will use that first argument as a directory to initialize the project in which doesn't exist because it is a file.

Now I don't know why this happens but this seems like an issue with the script which I don't have knowledge/time to debug.

I am using `nvm` and `fnm` to manage multiple node versions and they both work fine so maybe `libalternative` has a bug.

**Comment by ancwrd1** [comment]
It's not related to libalternative, I have mentioned above that you can reproduce it simply by making a shell script wrapper called `/usr/bin/node` which calls `/usr/bin/node18`.
