### ISSUE TITLE
The angular template has disappeared from version 2.5 :(

### ISSUE THREAD

**Issue by ProfeJulianLasso** [tauri-apps/create-tauri-app#197]
I don't know if it was by mistake or what happened, but when a project is created, Angular no longer appears to use it as a template, is it possible to return it please?

**Comment by FabianLars** [comment]
It's still there for me 
![grafik](https://user-images.githubusercontent.com/30730186/193405621-a4dbb98c-28f2-4e4f-a681-9b89c63ca6e4.png)

Or did i misunderstand the problem?

**Comment by ProfeJulianLasso** [comment]
@FabianLars 

![2022-10-01_08-42](https://user-images.githubusercontent.com/98534497/193412423-1e7925f0-cb09-4079-80cb-376dac07a367.png)

I apologize for my mistake, I was executing the command

`cargo create-tauri-app`

the correct command for this occasion is

`npm create tauri-app@latest`

In this last command, everything works perfect, thank you very much for the great effort of the team.

Again I apologize for my mistake

**Comment by FabianLars** [comment]
Your cargo installation of create-tauri-app is probably outdated? You can update it by re-installing it via `cargo install create-tauri-app`
