### ISSUE TITLE
[bug]: Unknown Syntax Error: Unsupported option name ("--ignore-scripts").

### ISSUE THREAD

**Issue by GiantappMan** [tauri-apps/create-tauri-app#2]
### Describe the bug

yarn create tauri-app  
windows10

### Reproduction

yarn create tauri-app  
windows10

### Platform and versions

```shell
Missing script: "tauri"
```

### Additional context

 yarn create tauri-app
➤ YN0000: ┌ Resolution step
➤ YN0000: └ Completed in 14s 982ms
➤ YN0000: ┌ Fetch step
➤ YN0000: └ Completed
➤ YN0000: ┌ Link step
➤ YN0000: └ Completed in 0s 526ms
➤ YN0000: Done in 15s 742ms

? What is your app name? test0
? What should the window title be? test0
? Would you like to add a UI recipe? Vanilla.js
===== running initial command(s) =====
===== installing any additional needed deps =====
Installing @tauri-apps/cli...
Unknown Syntax Error: Unsupported option name ("--ignore-scripts").

$ yarn add [--json] [-E,--exact] [-T,--tilde] [-C,--caret] [-D,--dev] [-P,--peer] [-O,--optional] [--prefer-dev] [-i,--interactive] [--cached] [--mode #0] ...
Error with command: yarn
Error: Error: Command failed with exit code 1: yarn add --dev --ignore-scripts @tauri-apps/cli
    at C:\Users\user\AppData\Local\Yarn\Berry\cache\create-tauri-app-npm-1.0.0-beta-rc.4-90c8c4d827-8.zip\node_modules\create-tauri-app\dist\index.js:59:15
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\user\AppData\Local\Yarn\Berry\cache\create-tauri-app-npm-1.0.0-beta-rc.4-90c8c4d827-8.zip\node_modules\create-tauri-app\dist\index.js:36:65)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by amrbashir** [comment]
for now you can use yarn1 to create the project, then after it is created, use yarn2+
