### ISSUE TITLE
Unable to create project with selected template ( v. 2.6.0)

### ISSUE THREAD

**Issue by DmitrySorda** [tauri-apps/create-tauri-app#208]
`success Installed "create-tauri-app@2.6.0" with binaries:
      - create-tauri-app

✔ Choose your package manager · cargo
error: the svelte template is not suppported for the cargo package manager
       possible templates for cargo are: [vanilla, yew]
error Command failed.
Exit code: 1
`

**Comment by amrbashir** [comment]
Svelte doesn't work with Cargo as the package manager as described in the error, you have to choose another package manager if you want to use Svelte or use another template that works with cargo, such as `vanilla` and `yew`.

I think you invoked the cli like this `cargo create-tauri-app --template svelte` and this is the second time someone has went this same path so I think I need to only prompt the supported package manager for the template.
