### ISSUE TITLE
[Feature request] Add Qwik

### ISSUE THREAD

**Issue by k4my4b** [tauri-apps/create-tauri-app#256]
Could you please add [Qwik](https://qwik.builder.io/) to the list of UI templates, many thanks!

**Comment by amrbashir** [comment]
I am afraid this won't be possible, the amount of Nodejs based templates are huge at this moment and this will be changed soon. see #258 

I think a Qwik template should be a community template, that is submitted to https://github.com/tauri-apps/awesome-tauri and potentially could be used through CTA once #3 is implemented.
