### ISSUE TITLE
Changes for `create-tauri-app@3`

### ISSUE THREAD

**Issue by amrbashir** [tauri-apps/create-tauri-app#258]
![image](https://user-images.githubusercontent.com/48618675/206855870-37d06ccb-a13e-4397-9412-04a6b073db95.png)
	
- [ ] Remove unpopular templates and keep only 5 Node.js-based templates at a time.
- [ ] Flavor of templates which will be mostly `javascript` and `typescript` will be prompted separately after choosing one of the templates
- [ ] Add more Rust-based templates, `leptos` and `dioxus` seems like good-candidates, however leptos is not even `0.1` yet and `dioxus` already offers a desktop framework of their own.
- [ ] `--alpha` and `--mobile` options

**Comment by Khaomi** [comment]
I think Vite should be added to the template too, as it can be a base for adding other framework, and Vite is a really popular build tool. or you could swap Vite for webpack since it's more popular than Vite.

**Comment by FabianLars** [comment]
All nodejs based templates use or will use vite

**Comment by Khaomi** [comment]
Thank you for the clarification!

**Comment by glyh** [comment]
@kwrooijen could you unarchive the template https://github.com/kwrooijen/tauri-cljs, given this?

**Comment by kwrooijen** [comment]
@glyh Sure, I'll take a look later today. I'd still need to update tauri within the https://github.com/kwrooijen/tauri-cljs project, otherwise it won't work.

**Comment by simonhyll** [comment]
Wouldnt it be better with more templates but a better CLI for selecting which one to use?

I'm thinking kinda like:
Javascript/Typescript/Rust - Typescript
React/Vue/Svelte - Vue
Nuxt/Vue CLI - Nuxt

I feel like removing templates makes it harder for people to get started, I've already had to help 2 people get started with Nuxt. More templates means easier to get developers into Tauri, and I for one would certainly welcome easily setting up new apps in my chosen framework, and dont see why other frameworks get "special treatment"

One alternative for me ofc is to offer my own template project, but it feels weird that the official version cuts down on templates, especially when they are already developed

**Comment by FabianLars** [comment]
@simonhyll afaik the idea is to compensate the reduced amount of templates with this: <https://github.com/tauri-apps/create-tauri-app/issues/3>.

I think the main problem here is the workload/maintenance burden idk

**Comment by amrbashir** [comment]
@simonhyll even after refining the selection flow and separating it into multiple phases, you will still end up with so many frameworks to maintain (keep in mind that in the future, tauri will support more languages other than Rust and each lang will bring their set of templates as well.

> One alternative for me ofc is to offer my own template project, but it feels weird that the official version cuts down on templates, especially when they are already developed.

This is fine, and CTA could potentially download and use that on-demand like how crate-vite calls to create-vite-extra. Also, I want to encourage more templates to be submitted to awesome-tauri repo instead of contributing them to the tool.

**Comment by ModProg** [comment]
As leptos had it's first release now, would you merge a PR adding a leptos template or would you rather wait a little longer.

**Comment by amrbashir** [comment]
@ModProg the linked PR has a template for leptos, the PR is on hold for now until the next alpha release of tauri but for now you can try it from git using:
```
cargo install create-tauri-app --git https://github.com/tauri-apps/create-tauri-app --branch 'cta@3'
cargo create-tauri-app
```
