### ISSUE TITLE
create-tauri-app for sveltekit is broken

### ISSUE THREAD

**Issue by rakataprime** [tauri-apps/create-tauri-app#259]
yarn create tauri-app with sveltekit or sveltekit-ts are both failing currently after running yarn install && yarn dev on linux 

I believe this may be related to [this vite issue](https://github.com/vitejs/vite/issues/11190)  with mismatched plugin and vite  v4.0.0.  

The yarn create tauri-app for svelte and svelte-ts are both still working.  I think this may  be fixed by pinning dependency or updating vite/sveltekit dependencies. 

```
$ yarn dev
yarn run v1.22.19
$ vite dev
failed to load config from /vite.config.js
error when starting dev server:
file://node_modules/@sveltejs/kit/src/exports/vite/dev/index.js:6
import { isCSSRequest } from 'vite';
         ^^^^^^^^^^^^
SyntaxError: The requested module 'vite' does not provide an export named 'isCSSRequest'
    at ModuleJob._instantiate (node:internal/modules/esm/module_job:123:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:189:5)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:533:24)
```

**Comment by FabianLars** [comment]
it's being fixed in https://github.com/tauri-apps/create-tauri-app/pull/257 - thanks for the report

**Comment by ghost** [comment]
it is failing again

**Comment by FabianLars** [comment]
@regnou There is no svelte**kit** template anymore, could you share the errors you're getting and the steps you took to get there please?

**Comment by ghost** [comment]
https://github.com/oneezy/monorepo/issues/12

**Comment by FabianLars** [comment]
Alright, thanks. There's nothing we can do on our side for you, so try doing the same we did in the PR i linked above: https://github.com/tauri-apps/create-tauri-app/pull/257/files#diff-0b1c6ded4854f21db9e99e347d7c9e15c96dbc8962336cab843024127d7b18ed
