### ISSUE TITLE
Add preprocess config to svelte.config.js

### ISSUE THREAD

**Issue by andradei** [tauri-apps/create-tauri-app#276]
Add the configuration for preprocessing automatically (found in https://tauri.app/v1/guides/getting-started/setup/sveltekit#sveltekit-in-ssg-mode).

This is so users don't have to do it manually.

```js
import adapter from '@sveltejs/adapter-static' // This was changed from adapter-auto
import preprocess from 'svelte-preprocess' // <------------------------ THIS

/** @type {import('@sveltejs/kit').Config} */
const config = {
  // Consult https://github.com/sveltejs/svelte-preprocess
  // for more information about preprocessors
  preprocess: preprocess(),  // <------------------------ THIS

  kit: {
    adapter: adapter(),
  },
}

export default config
```

Looks like things changed a bit, `vite.config.js` seems to have the correct config, but `svelte.config.js` missed some config for some reason:

![CleanShot 2022-12-30 at 12 43 22@2x](https://user-images.githubusercontent.com/2653546/210106851-631ed0ab-41e2-4989-b102-8a61e2334991.png)

**Comment by lumirth** [comment]
Seconding this—when creating a svelte-ts or sveltekit-ts project, you'll run into a Vite error "unexpected token" when adding type annotations in a `.svelte` file(or at least that's where I kept running into it).

Adding svelte-preprocess fixes this, but it should probably come built into the template.
