### ISSUE TITLE
Recipe for Nodejs sidecar server or Rust http server?

### ISSUE THREAD

**Issue by Drecula** [tauri-apps/create-tauri-app#282]
Hi,

create-tauri-app is really useful!

Would it be possible to create a receipt for either a Rust http server or a NodeJs sidecar server,
including comms back to FE (React is what I'm most familiar with, but Vanilla & Svelte are OK too).

Thanks!

**Comment by amrbashir** [comment]
This tool main purpose is to create a base project, it will not come pre-configured with anyting else but the basics. This idea is better suited to be a community project.
