### ISSUE TITLE
Stale output! Your loaded JS was not produced by the running shadow-cljs instance. Is the watch for this build running?

### ISSUE THREAD

**Issue by glyh** [tauri-apps/create-tauri-app#285]
I got the above errors when running `yarn tauri dev` under a clojusrescript template.

**Comment by glyh** [comment]
The error is gone after a refresh though

**Comment by amrbashir** [comment]
clojurescript template is being removed in #284 , but based on the error, looks like you have two instances of shadow-cljs running or something.

**Comment by glyh** [comment]
Why is clojurescript template being removed?

**Comment by FabianLars** [comment]
We want to have only really few official templates: https://github.com/tauri-apps/create-tauri-app/issues/258 mainly to reduce our workload, especially for rarely used templates like clojurejs which none of the team members use.
To compensate the lost templates we will likely implement support for custom/community recipes: https://github.com/tauri-apps/create-tauri-app/issues/3 - but even if not, you can still create the clojure projects yourself and add tauri to it afterwards, or use community templates without create-tauri-app: https://github.com/tauri-apps/awesome-tauri/#templates (there's no clojure one yet)

**Comment by glyh** [comment]
@kwrooijen could you unarchive the template https://github.com/kwrooijen/tauri-cljs, given this?
