### ISSUE TITLE
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Erro

### ISSUE THREAD

**Issue by imblowsnow** [tauri-apps/create-tauri-app#300]
i use `yarn create tauri-app` and `yarn tauri dev`
it is error: 

thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Error { kind: NotFound, message: "program not found" }', src\interface\rust.rs:762:69
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Done in 1.50s.

**Comment by FabianLars** [comment]
This error means that you don't have rust installed, or that tauri just couldn't find it. Did you follow the setup guide? https://tauri.app/v1/guides/getting-started/prerequisites

p.s. the error will be improved in v1.3
