### ISSUE TITLE
Should spaces be converted?

### ISSUE THREAD

**Issue by btea** [tauri-apps/create-tauri-app#301]
If the initialized project name contains spaces, should it be converted, such as replaced with `-`.

**Comment by amrbashir** [comment]
yeah, it gets replaced with `-`, did it not get replaced for you? if not, let me know the steps to reproduce.

**Comment by btea** [comment]
![image](https://user-images.githubusercontent.com/24516654/213039068-ecb6bd7d-9c73-48df-803e-4dedb83a36e8.png)

**Comment by amrbashir** [comment]
You can see in the second question it got converted to `-`.

**Comment by btea** [comment]
Yes, the `Package name` were converted, but the project name spaces were not.  As shown in the screenshot, running `cd tauri test` after the initialization is complete will fail. Therefore, I am wondering whether it is necessary to convert the spaces in the project name to `-`.

**Comment by amrbashir** [comment]
Ah I see what you mean, and I actually released a version today https://github.com/tauri-apps/create-tauri-app/releases/tag/create-tauri-app-v2.7.7 with a fix for that specifically. It will wrap the path in quotes if it contains spaces
