### ISSUE TITLE
Project names cannot contain spaces at the end?

### ISSUE THREAD

**Issue by btea** [tauri-apps/create-tauri-app#308]
During initialization, if the project name contains a space at the end, an error will be thrown and the process will exit.

**Comment by amrbashir** [comment]
I can't seem to reproduce this, can you explain the steps to reproduce?

**Comment by btea** [comment]
For example, when I type `test `(end of character contains spaces) and continue execution, it will exit.

![image](https://user-images.githubusercontent.com/24516654/213827149-4030782c-cdc2-4512-9f69-77566caf97cc.png)

**Comment by amrbashir** [comment]
thank you, this is fixed now.

**Comment by btea** [comment]
you are so efficient. 👍
