### ISSUE TITLE
[bug]  missing tailwind package (arch linux, npm, next-ts)

### ISSUE THREAD

**Issue by antonio-hickey** [tauri-apps/create-tauri-app#315]
### Describe the bug

I just did a fresh install on arch linux using npm for package manager, and next-ts for framework. When I ran the `npm run tauri dev` I got a missing module error for `tailwindcss`. Obviously this can just be fixed by manually installing, but I figured this was a bug as since it requires tailwind it should be installed within build.

EDIT: also missing tailwindcss dependencies for next.js ( `autoprefixer` & `postcss` ) and I had to manually initialize tailwind ( `npx tailwindcss init -p` )

### Reproduction

1. OS: Arch Linux (btw)
2.  Create tauri app  (`sh <(curl https://create.tauri.app/sh)`)
3.  Select npm for package manager ( sorry cargo :cry: )
4. Select next-ts for framework
5. Run `npm run tauri dev `
6.  * :exploding_head: * boom computer blows up ( missing tailwind css module error )

### Expected behavior

For tailwindcss module and it's dependencies to be installed and initialized as part of the build.

### Platform and versions

```
[H¡ckey] ➜ flow (! tauri-app)! npm run tauri info 

> flow@0.0.0 tauri
> tauri info


Environment
  › OS: Arch Linux Unknown X64
  › Node.js: 19.3.0
  › npm: 9.2.0
  › pnpm: Not installed!
  › yarn: Not installed!
  › rustup: 1.25.1
  › rustc: 1.65.0
  › cargo: 1.65.0
  › Rust toolchain: stable-x86_64-unknown-linux-gnu 

Packages
  › @tauri-apps/cli [NPM]: 1.2.3
  › @tauri-apps/api [NPM]: 1.2.0
  › tauri [RUST]: 1.2.4,
  › tauri-build [RUST]: 1.2.1,
  › tao [RUST]: 0.15.8,
  › wry [RUST]: 0.23.4,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../dist
  › devPath: http://localhost:1420/
  › framework: React (Next.js)
  › bundler: Webpack

App directory structure
  ├─ src-tauri
  ├─ node_modules
  ├─ src
  ├─ .next
  └─ .vscode
```

### Additional context

I can help fix if someone can point me in the right direction, I'm assuming all I have to do is include the tailwindcss module to be apart of the modules installed within build.

**Comment by FabianLars** [comment]
I can't reproduce this at all. The template works fine for me with your reproduction steps. But tailwindcss is also not a nextjs dependency, so i don't really see where that error could come from 🤔

**Comment by antonio-hickey** [comment]
@FabianLars Yea tailwindcss isn't a nextjs dependency but it seem's like something in the starter template is using tailwindcss. I'll explore it more when I get home, but curious if you could post the output from `npm run tauri info` because it could be environment related.

**Comment by FabianLars** [comment]
basically the same as your output but on ubuntu
```bash
Environment
  › OS: Ubuntu 22.04 X64
  › Node.js: 18.13.0
  › npm: 8.19.3
  › pnpm: 7.25.1
  › yarn: 1.22.19
  › rustup: 1.25.1
  › rustc: 1.66.0
  › cargo: 1.66.0
  › Rust toolchain: stable-x86_64-unknown-linux-gnu

Packages
  › @tauri-apps/cli [NPM]: 1.2.3
  › @tauri-apps/api [NPM]: 1.2.0
  › tauri [RUST]: 1.2.4,
  › tauri-build [RUST]: 1.2.1,
  › tao [RUST]: 0.15.8,
  › wry [RUST]: 0.23.4,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../dist
  › devPath: http://localhost:1420/
  › framework: React (Next.js)
  › bundler: Webpack

App directory structure
  ├─ .next
  ├─ .vscode
  ├─ node_modules
  ├─ src-tauri
  └─ src
```

> but it seem's like something in the starter template is using tailwindcss

Neither my package.json nor the lock file mention it 🤔 for reference the package.json file:
```json
{
  "name": "ne",
  "private": true,
  "version": "0.0.0",
  "scripts": {
    "dev": "next dev -p 1420",
    "build": "next build && next export -o dist",
    "tauri": "tauri"
  },
  "dependencies": {
    "@tauri-apps/api": "^1.2.0",
    "next": "^13.0.0",
    "react": "^18.2.0",
    "react-dom": "^18.2.0"
  },
  "devDependencies": {
    "@tauri-apps/cli": "^1.2.2",
    "@types/node": "^18.7.11",
    "@types/react": "^18.0.17",
    "@types/react-dom": "^18.0.6",
    "typescript": "^4.7.4"
  }
}
```

**Comment by antonio-hickey** [comment]
Hmm just thought of something, I ran the create tauri app from within an existing npm project which is using tailwind & other npm packages, so this could be related to that. 

It's weird it only ran into the tailwind missing modules error though and not all the other modules I have in the parent directory. 

When I get home later today I'll try to create tauri app within a fresh directory, and close this issue if it works as expected.
