### ISSUE TITLE
create-tauri-app Version 3 failed!

### ISSUE THREAD

**Issue by ckken** [tauri-apps/create-tauri-app#349]
![image](https://user-images.githubusercontent.com/3890513/222618607-4d277444-d905-4f12-a687-286be1baf294.png)

**Comment by FabianLars** [comment]
This was fixed in https://github.com/tauri-apps/tauri-mobile/pull/110 and will be available with the tauri-mobile release (i think you have to re-run ios init then?)

In the meantime i _think_ you can remove the `name` from the `[lib]` section in Cargo.toml 🤔

**Comment by amrbashir** [comment]
The fix is actually in https://github.com/tauri-apps/tauri/pull/6387
