### ISSUE TITLE
The official docs are misleading

### ISSUE THREAD

**Issue by kholbekj** [tauri-apps/create-tauri-app#350]
I wonder if it would make sense to hold off merging drastic changes like removing sveltekit until ready to also update the docs?
Or have the install script from for example https://tauri.app/v1/guides/getting-started/setup/sveltekit point to a stable version of create-tauri-app? Definitely anyone new who's discovering tauri at the moment is going to be super confused when the official docs doesn't even have a Svelte (without kit) option, and yet the app has meanwhile gotten rid of sveltekit.

**Comment by amrbashir** [comment]
create-tauri-app isn't the same as the guides one the website, they aim to solve the same problem but in different ways and they don't need to have parity. l

We will be updating the docs to make this more obvious.
