### ISSUE TITLE
[bug]template works, but vscode told problems

### ISSUE THREAD

**Issue by me1ting** [tauri-apps/create-tauri-app#366]
The template works well(means `yarn tauri dev`,`yarn tauri build` works  well), but vscode works bad:

![Code_ewssS8QjN4](https://user-images.githubusercontent.com/52079867/224503705-7f7c3fe9-f494-4090-a084-2b58dcaaa22a.png)
![Code_hPxrFwhkkb](https://user-images.githubusercontent.com/52079867/224504299-faac51f7-c10c-4435-b3e2-46c411a76b96.png)

**Vue templates on vscode told similar problems.**

My steps:
```
yarn create tauri-app
✔ Project name · the-demo
✔ Choose which language to use for your frontend · TypeScript / JavaScript - (pnpm, yarn, npm)
✔ Choose your package manager · yarn
✔ Choose your UI template · Svelte - (https://svelte.dev/)
✔ Choose your UI flavor · TypeScript
```

My environment:
```
os: Windows x64
node: v18.14.0
vscode: last version
vscode plugins: 
    Tauri: last version
    Svelete for VS Code: last version
    Volar: last version
    rust-analyzer: last version
```

**Comment by amrbashir** [comment]
I don't see any errors using the same environment as you do, did you install the template dependencies by running `yarn install` inside the created template? if not, run `yarn install` and the errors should go away.

**Comment by me1ting** [comment]
I do use `yarn`, my problem is that vscode tells problem but eveything runs well when using `yarn tauri dev` and `yarn tauri build`.

Although it does not affect the development, it may be a problem with my environment, thank you anyway.

**Comment by me1ting** [comment]
@amrbashir The problem fixed when i changed package manager from `yarn` to `npm`.

Thank you.

**Comment by amrbashir** [comment]
were you using yarn version 2 or higher?

**Comment by me1ting** [comment]
~~I used the default yarn of npm(v18.14.0)~~ I used the stable version of yarn, the version number is `3.4.1`.

**Comment by amrbashir** [comment]
yeah I think that is an issue with yarn v2 and higher (yarn v1 works fine)

**Comment by amrbashir** [comment]
Yup seems like an issue with yarn itself, see https://github.com/yarnpkg/berry/issues/4872

**Comment by me1ting** [comment]
I think the question is [pnp](https://yarnpkg.com/features/pnp), user should use [editor sdk](https://yarnpkg.com/getting-started/editor-sdks) at the same time(it really fixed my problem).

The template may need to add editor sdk integration, or remove pnp for yarn, or add document to tell users enable pnp/editor sdk by hands.

**Comment by amrbashir** [comment]
We assume by default that users are using yarn v1, we can't detect if they are using yarnv2 so we can't initialize the editor sdk for them.
