### ISSUE TITLE
[Feature Request]: add a workspace Cargo.toml at the root of project folder

### ISSUE THREAD

**Issue by escwxyz** [tauri-apps/create-tauri-app#388]
The Rust analyzer often fails to start with the error `can not discover workspace`.  

Can we add a `Cargo.toml` file with `src-tauri` as its member, to the templates?

**Comment by amrbashir** [comment]
What template did you encounter this with? rust-analyzer works fine for me with all templates, there is no need for a root `Cargo.toml` file.

**Comment by escwxyz** [comment]
> What template did you encounter this with? rust-analyzer works fine for me with all templates, there is no need for a root `Cargo.toml` file.

Thanks I am currently using the Solid template. 

My steps:

1. `cargo create-tauri-app`
2. Enter
3. `TypeScript / JavaScript`
4. `pnpm`
5. `Solid`
6. cd and install the deps
7. open the directory with vscode
8. rust-analyzer takes while and then fails
9. add a workspace Cargo.toml to the root and specify `src-tauri` as its member
10. reopen the project folder with vscode
11. it works now as expected, add the root target folder to .gitignore

**Comment by amrbashir** [comment]
I have tested theses templates multiple times with rust-analyzer and vscode and they work fine. It sounds to me like a bug in rust-analyzer.

**Comment by escwxyz** [comment]
> I have tested theses templates multiple times with rust-analyzer and vscode and they work fine. It sounds to me like a bug in rust-analyzer.

You're right, maybe related to https://github.com/rust-lang/rust-analyzer/issues/14477
