### ISSUE TITLE
Not working with Angular front-end

### ISSUE THREAD

**Issue by decheverri123** [tauri-apps/create-tauri-app#404]
After running create-tauri-app and npm install, npm run dev leads to the following error:
<img width="489" alt="image" src="https://user-images.githubusercontent.com/22533715/232139226-12c70555-6321-460d-b9fd-4dc9c517925b.png">
Adding "tauri":"tauri" to the scripts in angular.json does not work.
Edit: seems to be an issue with npm. Using yarn resolves issue.

**Comment by amrbashir** [comment]
Thanks for reporting this, we will fix it soon, for now, you can just add `"tauri": "tauri"` to the `scripts` object in `pacakge.json` and it will work
