### ISSUE TITLE
[bug] npm run tauri dev - Error The "beforeDevCommand" terminated with a non-zero status code.

### ISSUE THREAD

**Issue by andreescocard** [tauri-apps/create-tauri-app#411]
### Describe the bug

When running "npm run tauri dev" i got this error: 

```
> tauri-app@0.0.0 tauri
> tauri dev

     Running BeforeDevCommand (`npm run start --port 1420`)

> tauri-app@0.0.0 start
> ng serve 1420

Error: Invalid values:
  Argument: project, Given: "1420", Choices: "tauri"
       Error The "beforeDevCommand" terminated with a non-zero status code.
```

### Reproduction

Create new tauri project with typescript and angular and run tauri dev after install packages

### Platform and versions

```text
Environment
  › OS: Windows 10.0.22621 X64
  › Webview2: 112.0.1722.64
  › MSVC: 
      - Ferramentas de Build do Visual Studio 2019
  › Node.js: 18.16.0
  › npm: 9.5.1
  › pnpm: Not installed!
  › yarn: Not installed!
  › rustup: 1.26.0
  › rustc: 1.69.0
  › cargo: 1.69.0
  › Rust toolchain: stable-x86_64-pc-windows-msvc 

Packages
  › @tauri-apps/cli [NPM]: 1.2.3
  › @tauri-apps/api [NPM]: 1.2.0
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Error("unexpected end of input while parsing minor version number")', src\info.rs:502:41
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

### Additional context

I fixed the bug changing 2 lines in tauri.conf.json but it should generate the file with correct port after selecting options.
On build section, i change these 2 lines:

`
    "beforeDevCommand": "npm run start --port 1420",
    "devPath": "http://localhost:1420",
`

to

`
    "beforeDevCommand": "npm run start",
    "devPath": "http://localhost:4200",
`

**Comment by andreescocard** [comment]
Hi @amrbashir, looking on the commit i think the problem will persists because on angular the default port is 4200 and not 1420.

**Comment by FabianLars** [comment]
@andreescocard create-tauri-app's config will overwrite angulars default port: https://github.com/tauri-apps/create-tauri-app/commit/ca260fbefb9479db66a28e64730ff4d745eccee9#diff-c94484f43dcb633988ff7e0efa705554827c65bfc08ac8d82148869119381b37R5 - this also means you'd have to re-generate your template (or add the extra `--` to your beforeDevCommand in tauri.conf.sjon) to see the PR changes in action.

(In the other templates this is handled by a config file but ig angular can only do it as a cli flag?)

**Comment by andreescocard** [comment]
> @andreescocard create-tauri-app's config will overwrite angulars default port: [ca260fb#diff-c94484f43dcb633988ff7e0efa705554827c65bfc08ac8d82148869119381b37R5](https://github.com/tauri-apps/create-tauri-app/commit/ca260fbefb9479db66a28e64730ff4d745eccee9#diff-c94484f43dcb633988ff7e0efa705554827c65bfc08ac8d82148869119381b37R5) - this also means you'd have to re-generate your template (or add the extra `--` to your beforeDevCommand in tauri.conf.sjon) to see the PR changes in action.
> 
> (In the other templates this is handled by a config file but ig angular can only do it as a cli flag?)

You are right, tested here on a new project and it is working fine.
Thanks for explanation

**Comment by Rmtdi** [comment]
hello,I have the same problem,can you tell me how to fix that bug?

**Comment by Shrayn1447** [comment]
Hi, I also ran into this problem, I was helped by changing the postcss configuration extension with .js on .cjs
