### ISSUE TITLE
Use "irm" instead of "iwr -useb" in PowerShell.

### ISSUE THREAD

**Issue by mucookul** [tauri-apps/create-tauri-app#416]
In PowerShell, you can do:
```powershell
irm https://create.tauri.app/ps | iex
```
instead of:
```powershell
iwr -useb https://create.tauri.app/ps | iex
```

**Comment by amrbashir** [comment]
`irm` or `iwr`, both works similarly but with any of them, we still have to use `-useb` because some older versions of PowerShell couldn't parse the script correctly. 

Is there something am I missing here?

**Comment by mucookul** [comment]
Is this really an issue though, all modern versions of windows come with PowerShell 5.1 which works fine.

**Comment by mucookul** [comment]
PowerShell 4 also seems to work from this post at least: [Update Powershell through command line](https://superuser.com/questions/1287032/update-powershell-through-command-line)

**Comment by amrbashir** [comment]
cool, would you like to open a PR @Mukul1127 ?

**Comment by mucookul** [comment]
Created a pull request.
