### ISSUE TITLE
[bug] tauri android init is failed

### ISSUE THREAD

**Issue by Japanese-Beginner** [tauri-apps/create-tauri-app#428]
### Describe the bug

$npm create tauri-app -- --alpha
(v3.4.0)
->mobile
$cd XXXXX(project dir)
$npm install
$npm run tauri android init

> XXXXX@0.0.0 tauri
> tauri android init
       Error `tauri.conf.json` error on `tauri`: Additional properties are not allowed ('allowlist', 'updater' were unexpected)

[tauri](https://github.com/tauri-apps/tauri/tree/dev)/[tooling](https://github.com/tauri-apps/tauri/tree/dev/tooling)/[cli](https://github.com/tauri-apps/tauri/tree/dev/tooling/cli)
/schema.json
line.462
"additionalProperties": false
is reason?

### Platform and versions

```text
sorry npm run tauri info 
is error too.
```

**Comment by amrbashir** [comment]
This should be solved by https://github.com/tauri-apps/create-tauri-app/pull/424 , the latest release of tauri alpha brought some breaking changes, thanks for your patience. For now, in your `Cargo.toml` you can change `tauri` version to `2.0.0-alpha.8`and `tauri-build` version to `2.0.0-alpha.4` and it should work

**Comment by Japanese-Beginner** [comment]
thank you amrbashir.
I tried your advise.
but another error occred in not only tauri@2.0.0-alpha.8 and tauri-build@2.0.0-alpha.4
but also tauri@2.0.0-alpha.9 and tauri-build@2.0.0-alpha.5.
I give up to use 2.0.0-alpha.
I use tauri@1.3 and tauri-build@1.3 waiting for v2.0 become stable
