### ISSUE TITLE
broken solidjs-ts template

### ISSUE THREAD

**Issue by BERADQ** [tauri-apps/create-tauri-app#463]
at /vite.config.ts line 5

没有与此调用匹配的重载。
  第 1 个重载(共 3 个)，“(config: UserConfig): UserConfig”，出现以下错误。
    类型“() => Promise<{ plugins: Plugin_2[]; clearScreen: boolean; server: { port: number; strictPort: boolean; }; envPrefix: string[]; build: { target: string; minify: string | boolean; sourcemap: boolean; }; }>”与类型“UserConfig”不具有相同的属性。
  第 2 个重载(共 3 个)，“(config: Promise<UserConfig>): Promise<UserConfig>”，出现以下错误。
    类型“() => Promise<{ plugins: Plugin_2[]; clearScreen: boolean; server: { port: number; strictPort: boolean; }; envPrefix: string[]; build: { target: string; minify: string | boolean; sourcemap: boolean; }; }>”的参数不能赋给类型“Promise<UserConfig>”的参数。
  第 3 个重载(共 3 个)，“(config: UserConfigExport): UserConfigExport”，出现以下错误。
    类型“() => Promise<{ plugins: Plugin_2[]; clearScreen: boolean; server: { port: number; strictPort: boolean; }; envPrefix: string[]; build: { target: string; minify: string | boolean; sourcemap: boolean; }; }>”的参数不能赋给类型“UserConfigExport”的参数。
      不能将类型“() => Promise<{ plugins: Plugin_2[]; clearScreen: boolean; server: { port: number; strictPort: boolean; }; envPrefix: string[]; build: { target: string; minify: string | boolean; sourcemap: boolean; }; }>”分配给类型“UserConfigFnObject”。
        类型“Promise<{ plugins: Plugin_2[]; clearScreen: boolean; server: { port: number; strictPort: boolean; }; envPrefix: string[]; build: { target: string; minify: string | boolean; sourcemap: boolean; }; }>”与类型“UserConfig”不具有相同的属性。
![image](https://github.com/tauri-apps/create-tauri-app/assets/78293733/fa5a9179-f6f8-4ccd-a181-89622d30129a)

**Comment by amrbashir** [comment]
I couldn't reproduce the error but I opened #464 to maybe fix this.
