### ISSUE TITLE
`--port` argument is ignored when running `pnpm tauri dev`

### ISSUE THREAD

**Issue by samrat** [tauri-apps/create-tauri-app#473]
`pnpm tauri dev` accepts a `--port` argument but because of the way `create-tauri-app` sets up the Vite config(for example, [the one for Svelte](https://github.com/tauri-apps/create-tauri-app/blob/dev/packages/cli/fragments/fragment-svelte/%25(mobile)%25vite.config.js#L19)), the passed argument is ignored.

**Comment by amrbashir** [comment]
`--port` is an option for the CLI internal devServer which is only used when you're not using a devServer on your own, but in your case, you're using vite.

If you want to change the port, then you need to change it in your vite.conf.json then in tauri.conf.json
