### ISSUE TITLE
[feat] Vanilla.js template in create-tauri-app should use JS and CSS

### ISSUE THREAD

**Issue by kornelski** [tauri-apps/create-tauri-app#48]
### Describe the problem

`crate-tauri-app` has an option to create "Vanilla.js (html, css, and js without the bundlers)" app. However, it creates only the HTML part of it, but doesn't include any CSS or JS.

I don't know where to put JS. If there are no bundles, how does it get bundled into the final native application? I don't know if I can just create `foo.js` anywhere and reference it through a `<script>` in `dist/index.html`. Does it require any special path, syntax? There is an overwhelming amount of configuration in Tauri, and I'm afraid I need to add some `"myJavaScriptIsHere":"./js/"` to `tauri.conf.json`. Even if I don't need to, I'd rather have a proof of that in the form of a working JS example in the app template.

### Describe the solution you'd like

I'd like the template in `crate-tauri-app` contain JS and CSS files too, so that it's clear how configuration for more than just a single HTML file works, and what is the preferred syntax for these things.

### Alternatives considered

I've tried putting JS directly in the `dist/index.html` like this:

```js
  <script type="module">
    import { listen } from '@tauri-apps/api/event'
  </script>
```

and it fails with a runtime error:

> TypeError: Module specifier, '@tauri-apps/api/event' does not start with "/", "./", or "../". Referenced from tauri://localhost

so I'm not sure if it's even possible to use Tauri's API at all from the Vanilla template. An example with working JS using these imports successfully would be greatly appreciated.

### Additional context

There is an overwhelming amount of configuration in Tauri. The configuration-over-convention approach is opposite of Rust's philosophy, and it's a barrier for me, because it's not easy to look at other Tauri apps to learn from — they're all different and incompatible due to having their snowflake configuration.

**Comment by GregorBoxer-sudo** [comment]
ive got exactly the same problems. have you got it working? I dont want to use vue, svelte, react or anything like that. Just plain js!

**Comment by amrbashir** [comment]
Until I update the vanilla template, here is what you need to do:
1. Any `.js` or `.css` files should be in `dist` directory, along with `index.html` (you can have nested dirs)
	```
  	dist
   	 |_ index.html
  	 |_ styles.css
   	 |_ script.js
  	src-tauri
 	```
2. Reference the `.js` or `.css` relative to `index.html`.
   - css:
		```html
		<link rel="stylesheet" href="styles.css">
		```
   - js:
   		```html
   		<script src="script.js"></script>
   		```
3. To Use tauri APIs, enable [`withGlobalTauri`](https://tauri.studio/v1/api/config#buildconfig.withglobaltauri) in `tauri.conf.json` and use it in js
	```js
	// all APIs under `window.__TAURI` object are the same as `@tauri-apps/api` npm package.
	const { invoke } = window.__TAURI__.tauri;
	const { readTextFile } = window.__TAURI__.fs;
	```
