### ISSUE TITLE
[feat] Add support for bun

### ISSUE THREAD

**Issue by turbomaster95** [tauri-apps/create-tauri-app#490]
### Describe the problem

I want to make a tauri app using bun like:
`bun create tauri-app@latest`

### Describe the solution you'd like

I would like you to add bun support for tauri-app@latest

**Comment by FabianLars** [comment]
Ah i forgot, this was already added in https://github.com/tauri-apps/create-tauri-app/pull/481 so it will be available in the next release of create-tauri-app
