### ISSUE TITLE
[bug] Outdated `@tauri-apps/api` breaks ipc

### ISSUE THREAD

**Issue by mchao123** [tauri-apps/create-tauri-app#496]
### Describe the bug

I encountered an issue while using the 2.0 beta version of our project. When selecting TypeScript as the backend language, the template does not seem to be correctly created, and the backend code remains in Rust. Additionally, when running the demo, I receive errors in the console.

Could you please take a look and help resolve this issue? Let me know if you need any further information or code snippets. Thank you!
<img width="456" alt="image" src="https://github.com/tauri-apps/tauri/assets/24653378/1f17fe84-7d53-4d68-99d4-d337f105e3fe">

### Platform and versions

```text
[✔] Environment
    - OS: Windows 10.0.22621 X64
    ✔ WebView2: 117.0.2045.43
    ✔ MSVC:
        - Visual Studio Community 2022
        - Visual Studio ���ɹ��� 2022
    ✔ rustc: 1.71.1 (eb26296b5 2023-08-03)
    ✔ Cargo: 1.71.1 (7f1d04c00 2023-07-29)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (default)
    - node: 20.2.0
    - pnpm: 8.6.0
    - yarn: 1.22.19
    - npm: 9.6.6

[-] Packages
    - tauri [RUST]: 2.0.0-alpha.14
    - tauri-build [RUST]: 2.0.0-alpha.8
    - wry [RUST]: 0.33.0
    - tao [RUST]: 0.22.2
    - @tauri-apps/api [NPM]: 2.0.0-alpha.4
    - @tauri-apps/cli [NPM]: 2.0.0-alpha.9

[-] App
    - build-type: bundle
    - CSP: unset
    - distDir: ../dist
    - devPath: http://localhost:1420/
    - framework: Vue.js
    - bundler: Vite
```

**Comment by FabianLars** [comment]
We may have to update the create-tauri-app templates for the latest alpha version, thanks for the report!

Also, there is no typescript **backend**. The question is about whether your frontend should use plain javascript or typescript. The backend will always be Rust.

**Comment by FabianLars** [comment]
Yeah, it works after upgrading `@tauri-apps/api` - gonna move this issue to the CTA repo, thanks again.

**Comment by mchao123** [comment]
> 我们可能需要更新最新 alpha 版本的创建金牛座应用程序模板，感谢您的报告！
> 
> 此外，没有打字稿**后端**。问题是关于你的前端应该使用纯JavaScript还是打字稿。后端将永远是 Rust。

Thank you for your reply. I was able to solve the issue by using "pnpm add @tauri-apps/api@next".
By the way, the backend language selection in the installation guide is really strange. Just out of curiosity, does the team have any plans to use TypeScript or JavaScript for backend development? The recent bun runtime is really impressive

**Comment by FabianLars** [comment]
> By the way, the backend language selection in the installation guide is really strange

Do you have a link/screenshot? I don't see anything were we talk about backend languages.

>  Just out of curiosity, does the team have any plans to use TypeScript or JavaScript for backend development?

Nothing specific but we'd like to add support for more backend languages and it's on the roadmap. This is our main tracking issue (not much activity because we didn't start working on it yet): https://github.com/tauri-apps/tauri/issues/4670

**Comment by mchao123** [comment]
> > 顺便说一下，安装指南中的后端语言选择真的很奇怪
> 
> 你有链接/屏幕截图吗？当我们谈论后端语言时，我没有看到任何东西。
> 
> > 只是出于好奇，团队是否有计划使用 TypeScript 或 JavaScript 进行后端开发？
> 
> 没有什么具体的，但我们想添加对更多后端语言的支持，它在路线图上。这是我们的主要跟踪问题（没有太多活动，因为我们还没有开始处理它）：[tauri-apps/tauri#4670](https://github.com/tauri-apps/tauri/issues/4670)
Creating a page looks something like this.
```
PS C:\Users\23068\Desktop\auto\tauri> pnpm create tauri-app --alpha
AppData/Local/pnpm/store/v3/tmp/dlx-9812 |   +2 +
Packages are copied from the content-addressable store to the virtual store.
  Content-addressable store is at: C:\Users\23068\AppData\Local\pnpm\store\v3
  Virtual store is at:             AppData/Local/pnpm/store/v3/tmp/dlx-9812/node_modules/.pnpm
AppData/Local/pnpm/store/v3/tmp/dlx-9812 | Progress: resolved 11, reused 2, downloaded 0, added 2, done
✔ Project name · t
? Choose which language to use for your frontend ›
❯ TypeScript / JavaScript  (pnpm, yarn, npm)
  Rust
```

**Comment by FabianLars** [comment]
Any specific feedback on how we can improve that? Because it does specify `frontend` language in the question.

It mainly tries to ask whether your frontend needs npm support or not (like yew.rs - rust based frontend frameworks)

**Comment by mchao123** [comment]
This is confusing for beginners, maybe it's just my poor English, sorry.
