### ISSUE TITLE
.primitives in create tauri-app --alpha

### ISSUE THREAD

**Issue by szuke** [tauri-apps/create-tauri-app#515]
When creating an app using the following: 
`pnpm create tauri-app --alpha`

the main.js contains
`const { invoke } = window.__TAURI__.tauri;`

which should be 
`const { invoke } = window.__TAURI__.primitives;`

packages/cli/fragments/fragment-vanilla/src/main.js

**Comment by FabianLars** [comment]
This is part of https://github.com/tauri-apps/create-tauri-app/pull/513, thanks for the report :)
