### ISSUE TITLE
Cant use create-tauri-app due to error.

### ISSUE THREAD

**Issue by stellaris-lunae** [tauri-apps/create-tauri-app#541]
Speaks for itself:

yarn create tauri-app
yarn create v1.22.21
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...

success Installed "create-tauri-app@3.11.1" with binaries:
      - create-tauri-app
/usr/local/share/.config/yarn/global/node_modules/create-tauri-app/create-tauri-app.js:55
  return userAgent.split(" ")[0]?.split("/")[0];
                                 ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47
error Command failed.
Exit code: 1
Command: /usr/local/bin/create-tauri-app
Arguments:
Directory: /home/dragon/WebBundle
Output:

Ubuntu - WSL, works fine on windows. ( no i did not truncate the file that is it. )
Using yarn.

**Comment by amrbashir** [comment]
Looks like you're using an old Node.js version, What's your Node.js version?

**Comment by stellaris-lunae** [comment]
sorry for late reply. 

v20.10.0

**Comment by stellaris-lunae** [comment]
never mind just retested and it works, i think i updated

**Comment by ernstki** [comment]
In the case of a similar-although-not-precisely-the-same error message…

```
if (globalThis.navigator?.userAgent?.includes('Deno')) {
                         ^

SyntaxError: Unexpected token '.'
```

…I can confirm that updating (from a very old `node` from distro packages) to Node.js v22.something is a probable solution.

Here's Copilot's explanation of why: a new language feature.

> The error is due to **Node.js version incompatibility**. The code uses the **[optional chaining operator (`?.`)](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining)**, which was [introduced in **ES2020**](https://tc39.es/ecma262/2020/#sec-optional-chains) and requires **Node.js 14.0.0 or later**.

Today I learned!
