### ISSUE TITLE
Vanilla Rust frontend option generates javascript file instead of rust file

### ISSUE THREAD

**Issue by harisraharjo** [tauri-apps/create-tauri-app#550]
I don't know if this is the intended behavior but currently it generates main.js file instead of main.rs file for the frontend.
<img width="250" alt="image" src="https://github.com/tauri-apps/create-tauri-app/assets/34530664/8739844a-a946-4aac-86d9-230a2477fa02">

Version
create-tauri-app: 3.11.3

**Comment by amrbashir** [comment]
Yeah that is indeed the intended behavior, `vanilla` means raw HTML/CSS/JS, and you can't have a `main.rs` in vanilla without having a bundler which kinda beats the purpose of the `vanilla`
