### ISSUE TITLE
@latest doesn't work for yarn

### ISSUE THREAD

**Issue by Majora320** [tauri-apps/create-tauri-app#62]
In commit d462775742db185d6d595c57b44dde8b5e6719e0, `@latest` was added to the create subcommands for each package manager. This works with npm, but doesn't work for yarn, and instead causes the following error:

```
/bin/sh: line 1: /home/user/.yarn/bin/create-vite@latest: No such file or directory
error Command failed.
```

**Comment by amrbashir** [comment]
Thanks for the report, A fix will be publishd soon
