### ISSUE TITLE
`vite.config.ts` fails typecheck if uses standard modules like `path` and `fs`

### ISSUE THREAD

**Issue by betafcc** [tauri-apps/create-tauri-app#641]
In fresh TS + npm + Vanilla and TS + bun + Vanilla

On `vite.config.ts` you get the error:

```ts
import { resolve } from 'path' // Cannot find module 'path' or its corresponding type declarations.ts
```

Bundling still works fine even with the error there, but it can be confusing.

Even the [official docs on multiwindow](https://tauri.app/v1/guides/features/multiwindow/#creating-additional-html-pages) point to [vite docs on multiple entry points](https://vitejs.dev/guide/build.html#multi-page-app) which uses the `path` module, plus the `@tauri-apps/api/path`, which IS shown as availabe in that file, breaks when building the application.

### Temporary user solution

It can be solved by just installing `@types/node` (or `@types/bun`) as a dev dependency.

The problem is that the definitions will also infect all the `src/*` files, making people believe they have access to node/bun modules in runtime.

Unfortunately the only proper solution I can think is creating a separate `tsconfig.vite.json` and using [project-references](https://www.typescriptlang.org/docs/handbook/project-references.html) and use of the [types compiler option](https://www.typescriptlang.org/tsconfig#types) to pick and choose which types go where

**Comment by amrbashir** [comment]
it was deliberate not to include `@types/node` as it is not needed for the generated template to function properly and if users were to import these modules later, it should probably be their responsibility to include the types.
