### ISSUE TITLE
Wrong image paths in Default template for vanilla js contains

### ISSUE THREAD

**Issue by omar-abdelgawad** [tauri-apps/create-tauri-app#674]
I was using the `cargo create-tauri-app` with the following settings:
```console
$ cargo create-tauri-app 
✔ Project name · proj_name
✔ Choose which language to use for your frontend · TypeScript / JavaScript - (pnpm, yarn, npm, bun)
✔ Choose your package manager · npm
✔ Choose your UI template · Vanilla
✔ Choose your UI flavor · JavaScript

Template created! To get started run:
  cd proj_name
  npm install
  npm run tauri dev
``` 
but then when I manually opened the src/index.html file I noticed that the two image didn'at appear due to wrong paths specefied as they are missing the "." for specifying relative paths.
![image](https://github.com/tauri-apps/create-tauri-app/assets/113486195/ad641a04-21d7-4a54-9dff-5a4e11b7b945)

So `<img src="/assets/tauri.svg" class="logo tauri" alt="Tauri logo" />` should be corrected to `<img src="./assets/tauri.svg" class="logo tauri" alt="Tauri logo" />`
and the same for the second image.

**Comment by amrbashir** [comment]
closing, see https://github.com/tauri-apps/create-tauri-app/pull/675#pullrequestreview-2029821901
