### ISSUE TITLE
Restore sveltekit template for Tauri 2(as new option in addition to svelte)

### ISSUE THREAD

**Issue by qarmin** [tauri-apps/create-tauri-app#682]
I know that this was closed in #340, but according to comments, this feature is really desirable.

The problem is that on web, most of the tutorials use sveltekit, and is very hard to create an app with svelte and alternative tools.
I tried to do this, but failed when trying to use routing via svelte-routing - with sveltekit everything works fine.

If needed, there can be added a warning with potential drawbacks, but I think that user should have ability to choose sveltekit

**Comment by amrbashir** [comment]
check out this guide if you want to create a sveltekit template https://beta.tauri.app/start/frontend-configuration/sveltekit/

**Comment by qarmin** [comment]
At least for now, I've started using https://github.com/maiertech/template-tauri-sveltekit because it's the only template that has worked for me almost out of the box with Tauri 2 and sveltekit.
(Requires adding vitePreprocess to svelte.config.js and a few minor changes).

However, the problem is also that it cannot export app to mobile devices(actually I haven't tried it yet, but I'm almost sure that this not works).

**Comment by amrbashir** [comment]
We decided to replace Svelte with SvelteKit in https://github.com/tauri-apps/create-tauri-app/pull/708
