### ISSUE TITLE
critical bug in create tauri

### ISSUE THREAD

**Issue by joebnb** [tauri-apps/create-tauri-app#694]
```shell
 npx create-tauri-app 
/Users/never/Documents/workSpace/xxxxxxx/node_modules/create-tauri-app/index.js:263
    throw loadError;
    ^

Error: Cannot find module 'create-tauri-app-darwin-x64'
Require stack:
```

version:create tauri app 3.14.0

seems this version have some release problem cause not contain bin

if install 3.10.0 with `npx create-tauri-app ` works fine

**Comment by joebnb** [comment]
would have a test for tauri v2 when each version release,currently use 3.13.0 to init a v2 mobile project,will get error

```sh
✔ Would you like to setup the project for mobile as well? · yes

Template created! To get started run:
  cd lllix-app
  npm install
  npm run tauri android init
  npm run tauri ios init

For Desktop development, run:
  npm run tauri dev

For Android development, run:
  npm run tauri android dev

For iOS development, run:
```


```
npm run tauri android init

> test-app@0.0.0 tauri
> tauri android init

    Error `tauri.conf.json` error on `build`: Additional properties are not allowed ('devPath', 'distDir' were unexpected)
    Error `tauri.conf.json` error: Additional properties are not allowed ('package', 'tauri' were unexpected)

```

when i  remove this properties

```
npm run tauri ios init

> test-app@0.0.0 tauri
> tauri ios init

    Error `tauri.conf.json` error: Additional properties are not allowed ('package', 'tauri' were unexpected)
```



the default is 

```

{
    "build": {
        "beforeDevCommand": "npm run dev",
        "beforeBuildCommand": "npm run build"
    },
    "package": {
        "productName": "test-app",
        "version": "0.0.0"
    },
    "tauri": {
        "bundle": {
            "active": true,
            "targets": "all",
            "identifier": "com.tauri.dev",
            "icon": ["icons/32x32.png", "icons/128x128.png", "icons/128x128@2x.png", "icons/icon.icns", "icons/icon.ico"]
        },
        "security": {
            "csp": null
        },
        "windows": [
            {
                "fullscreen": false,
                "resizable": true,
                "title": "test-app",
                "width": 800,
                "height": 600
            }
        ]
    },
    "plugins": {
        "shell": {
            "open": true
        }
    }
}

```

**Comment by sundayha** [comment]
same issue

> ```shell
>  npx create-tauri-app 
> /Users/never/Documents/workSpace/xxxxxxx/node_modules/create-tauri-app/index.js:263
>     throw loadError;
>     ^
> 
> Error: Cannot find module 'create-tauri-app-darwin-x64'
> Require stack:
> ```
> 
> version:create tauri app 3.14.0
> 
> seems this version have some release problem cause not contain bin
> 
> if install 3.10.0 with `npx create-tauri-app ` works fine

**Comment by sundayha** [comment]
![Xnip2024-05-15_16-39-09](https://github.com/tauri-apps/create-tauri-app/assets/13161708/64842f33-8920-4625-ab23-73ffbdd6703d)
missing this "node_modules/create-tauri-app-darwin-x64"{.....}

**Comment by sundayha** [comment]
![Xnip2024-05-15_16-46-50](https://github.com/tauri-apps/create-tauri-app/assets/13161708/29f9f35f-c581-4c15-b21f-932e325b148a)
the create-tauri-app-darwin-x64 last version is 3.13.17

[create-tauri-app-darwin-x64](https://registry.npmjs.org/create-tauri-app-darwin-x64/)

**Comment by amrbashir** [comment]
thanks for investigating, I see it failed to publish darwin-x64 node module https://github.com/tauri-apps/create-tauri-app/actions/runs/9067860525/job/24914029295#step:9:69,  I will fix this today
