### ISSUE TITLE
Include `$schema` property in tauri.conf.json for intellisense

### ISSUE THREAD

**Issue by Ciantic** [tauri-apps/create-tauri-app#725]
VSCode has ability to check and provide intellisense for JSON files with schema.json, if you have property called "$schema", e.g.:

![image](https://github.com/tauri-apps/create-tauri-app/assets/64731/65b4bdf7-111f-4bb9-b9dc-32a4e89f414e)

[Tauri already has schema.json files made for this](https://github.com/tauri-apps/tauri/blob/dev/core/tauri-config-schema/schema.json), but it's not added by the templates, thus the users don't get the benefit of error checking in the editor.

You can try this intellisense by giving an URL to e.g. esm.sh like this: 
```json
{
    "$schema": "https://esm.sh/@tauri-apps/cli/schema.json",
    "build": {  
        "beforeBuildCommand": "",
        "beforeDevCommand": "",
        "devPath": "html",
        "distDir": "html",
        "withGlobalTauri": true
    }
}
```
Thanks!

**Comment by amrbashir** [comment]
you can also use `Tauri` vscode extension which provides completion for v1 and v2 apps, it will also check if you have the cli installed in `node_modules` and will use the schema from there if needed, otherwise will pull it from github.

**Comment by amrbashir** [comment]
I am gonna keep this issue open as I want to eventually support providing schema through `https://schema.tauri.app`, `https://schema.tauri.app/v1.2.4` and `https://schema.tauri.app/v2`. Once that is implemented, we can add that in the templates.
