### ISSUE TITLE
Created Desktop App Contains Only `main.rs` Entrypoint

### ISSUE THREAD

**Issue by tweidinger** [tauri-apps/create-tauri-app#744]
I think this topic has been discussed multiple times from multiple perspectives.
I remember a discord discussion between @simonhyll and @amrbashir where the conclusion was that we don't want compiler warnings or adding a default warning suppression leading to status quo but please correct me if I am wrong.

The current behavior is that whenever an app is bootstrapped only for desktop there is only the `main.rs` file created as the entrypoint, whereas on projects with mobile support `lib.rs` and `main.rs` are created.

Advantages:
- No cargo compiler warning
- Simpler base structure (only Desktop)

Disadvantages:
- Documentation is complicated
- Multiple project layouts
- Adding mobile support later will require refactor

I propose to change the default behavior to always create a lib and binary entrypoint, so our documentation and tooling can be built on a consistent project layout. I value this over adding a warning suppressing lint or a compiler warning for desktop projects.

**Comment by amrbashir** [comment]
Implemented in #748
