### ISSUE TITLE
generated tauri.conf.json doesn't work for v2

### ISSUE THREAD

**Issue by zoaha** [tauri-apps/create-tauri-app#745]
In trying to do a 1st run, I got:
```
Error `tauri.conf.json` error on `build`: Additional properties are not allowed ('devPath', 'distDir' were unexpected)
Error `tauri.conf.json` error: Additional properties are not allowed ('package', 'tauri' were unexpected)
```

**Comment by FabianLars** [comment]
I assume this is related to https://github.com/tauri-apps/plugins-workspace/issues/1615

So for some reason you ended up with a v1 project, so i have the same questions here as in the linked issue:
> Which npm version did you use? This command works for me but in your case it seemed to have ignored the --beta flag for some reason 🤔

> Also, which selections did you make in the create-tauri-app prompt?

**Comment by idheepan-pewcoe** [comment]
I had similar problems. 

I modified src-tauri/capabilities/default.json as the latest release of tauri has a breaking change.

{
  "$schema": "../gen/schemas/desktop-schema.json",
  "identifier": "default",
  "description": "Capability for the main window",
  "windows": ["main"],
  "permissions": [
    "core:path:default",
    "core:event:default",
    "core:window:default",
    "core:app:default",
    "core:image:default",
    "core:resources:default",
    "core:menu:default",
    "core:tray:default",
    "shell:allow-open"
  ]
}

> [758d28c8a](https://www.github.com/tauri-apps/tauri/commit/758d28c8a2d5c9567158e339326b765f72da983e) ([#10390](https://www.github.com/tauri-apps/tauri/pull/10390)) Core plugin permissions are now prefixed with core:, the core:default permission set can now be used and the core plugin name is reserved.
The tauri migrate tool will automate the migration process, which involves prefixing all app, event, image, menu, path, resources, tray, webview and window permissions with core:.

**Comment by zoaha** [comment]
same issue with latest `npm create tauri-app@latest -- --rc`
node v22.4
npm v10.8
on
windows 11 with latest updates

**Comment by zoaha** [comment]
turns out the cargo version works
cargo create-tauri-app --rc
npm version still does not

**Comment by amrbashir** [comment]
`npm create tauri-app@latest -- -- --rc` seems to work, looks like npm needs `-- --`, probably a bug in recent version of npm

**Comment by Kofituo** [comment]
If it doesn't work, why is it still on the official website?
https://tauri.app/start/frontend/leptos/
And what's the way forward. I think this issue needs to be reopened and addressed. It's frustrating to follow official instructions only to find out those instructions are outdated. Yet, there's no new instructions

**Comment by FabianLars** [comment]
What's broken on the linked page? The instructions look correct to me and I'm not really seeing the relation to this issue here.

**Comment by Kofituo** [comment]
> What's broken on the linked page? The instructions look correct to me and I'm not really seeing the relation to this issue here.

Sorry, my bad. I missed this line
https://tauri.app/start/create-project/#start-the-development-server
