### ISSUE TITLE
[dx] Default version doesn't work for mobile builds out of the box

### ISSUE THREAD

**Issue by chippers** [tauri-apps/create-tauri-app#749]
The default version used for generated projects uses `0.0.0` by default, which is not allowed in mobile (at least Android) builds. This adds friction to seeing the first android build, as you have to see the build fail, go edit a file, and then go to rebuild. A reasonable version would be `0.1.0` i believe.

> You must change the `version` in `tauri.conf.json`. The default value `0.0.0` is not allowed for Android package and must be at least `0.0.1`.`

`tauri info`:

```console
[✔] Environment
    - OS: Mac OS 14.6.0 X64
    ✔ Xcode Command Line Tools: installed
    ✔ rustc: 1.80.0 (051478957 2024-07-21)
    ✔ cargo: 1.80.0 (376290515 2024-07-16)
    ✔ rustup: 1.27.1 (2024-04-24)
    ✔ Rust toolchain: stable-aarch64-apple-darwin (default)
    - node: 20.16.0
    - pnpm: 9.6.0
    - npm: 10.8.1

[-] Packages
    - tauri [RUST]: 2.0.0-rc.0
    - tauri-build [RUST]: 2.0.0-rc.0
    - wry [RUST]: 0.41.0
    - tao [RUST]: 0.28.1
    - tauri-cli [RUST]: 2.0.0-rc.1
    - @tauri-apps/api [NPM]: 2.0.0-rc.0
    - @tauri-apps/cli [NPM]: 2.0.0-rc.1

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../dist
    - devUrl: http://localhost:1420/
    - bundler: Vite
```

**Comment by ekkolon** [comment]
@chippers `0.1.0` as initial version makes a lot of sense. 

Not only is this the version set by `cargo` when creating a new project, but it would also make sense from a semantic versioning perspective.
