### ISSUE TITLE
Impossible to install with `--locked`

### ISSUE THREAD

**Issue by Cerber-Ursi** [tauri-apps/create-tauri-app#757]
`Cargo.lock` currently contains reference to `proc-macro2 1.0.59`, which can't be compiled on newer Rust - https://github.com/rust-lang/rust/issues/113152, https://github.com/dtolnay/proc-macro2/pull/391. As consequence, it's impossible to use `cargo install create-tauri-app --locked`.

Initially found on [URLO](https://users.rust-lang.org/t/there-is-a-bug-in-typing-cargo-install-create-tauri-app-locked/116148).

**Comment by douxiaobo** [comment]
Okay. Thank you for post the issue.

**Comment by douxiaobo** [comment]
![image](https://github.com/user-attachments/assets/67d7b54e-78b0-4471-a6a3-9d91a074cc22)
