### ISSUE TITLE
deno: unrecognized subcommand

### ISSUE THREAD

**Issue by mahmoud-eltahawy** [tauri-apps/create-tauri-app#822]
running deno task tauri dev
gives error 
![screenshot](https://github.com/user-attachments/assets/cf6aba16-7eef-4cfe-a695-8c12e1563cb8)

**Comment by mahmoud-eltahawy** [comment]
however other scripts works like
deno task start

**Comment by amrbashir** [comment]
it seems that `deno install` might have used an older version of `@tauri-apps/cli` package, try to update the `@tauri-apps/cli`  version in your `package.json` to `2.0.3`

**Comment by mahmoud-eltahawy** [comment]
that works 

thanks
