### ISSUE TITLE
Vite browserlist

### ISSUE THREAD

**Issue by lorenzolewis** [tauri-apps/create-tauri-app#84]
Add this browserlist to the fragment templates to match the docs: `target: ['es2021', 'chrome97', 'safari13'],`

https://tauri.app/v1/guides/getting-started/setup/vite#create-the-frontend

**Comment by amrbashir** [comment]
see [7cdffe0](https://github.com/tauri-apps/create-tauri-app/commit/7cdffe08760d0b4dd686d14a994f388a4fbdb982) in the rewrite branch
