### ISSUE TITLE
"bunx create-tauri-app":  --dist-dir and --dev-path options are not valid

### ISSUE THREAD

**Issue by kornhill** [tauri-apps/create-tauri-app#844]
bunx create-tauri-app
We hope to help you create something special with Tauri!
You will have a choice of one of the UI frameworks supported by the greater web tech community.
This should get you started. See our docs at https://tauri.studio/
If you haven't already, please take a moment to setup your system.
You may find the requirements here: https://tauri.studio/en/docs/getting-started/setup-macos/
Press any key to continue...
? What is your app name? test-tauri
? What should the window title be? Tauri App
? What UI recipe would you like to add? create-vite (https://vitejs.dev/guide/#scaffolding-your-first-vite-project)
? Add "@tauri-apps/api" npm package? Yes
? Which vite template would you like to use? react-ts
>> Running initial command(s)

Scaffolding project in /Users/cliang/tmp/test-tauri...

Done. Now run:

  cd test-tauri
  bun install
  bun run dev

>> Installing any additional needed dependencies
- Installing @tauri-apps/cli@latest...

added 186 packages, and audited 187 packages in 16s

44 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
- Installing @tauri-apps/api@latest...

added 1 package, and audited 188 packages in 5s

45 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
>> Updating "package.json"
>> Running "tauri init"

> test-tauri@0.0.0 tauri
> tauri init --app-name test-tauri --window-title Tauri App --dist-dir ../dist --dev-path http://localhost:3000 --ci

error: unexpected argument '--dist-dir' found

Usage: npm run tauri init <--ci|--force|--log|--directory <DIRECTORY>|--tauri-path <TAURI_PATH>|--app-name <APP_NAME>|--window-title <WINDOW_TITLE>|--frontend-dist <FRONTEND_DIST>|--dev-url <DEV_URL>|--before-dev-command <BEFORE_DEV_COMMAND>|--before-build-command <BEFORE_BUILD_COMMAND>>

For more information, try '--help'.
Error with command: npm
Error: Error: Command failed with exit code 2: npm run tauri -- init --app-name test-tauri --window-title Tauri App --dist-dir ../dist --dev-path http://localhost:3000 --ci
    at /Users/cliang/.config/yarn/global/node_modules/create-tauri-app/dist/index.js:63:15
    at Generator.throw (<anonymous>)
    at rejected (/Users/cliang/.config/yarn/global/node_modules/create-tauri-app/dist/index.js:40:65)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

**Comment by amrbashir** [comment]
Looking at the errors, it seems like you're using a super old version of create-tauri-app, you should use the latest version, try `bunx create-tauri-app@latest` or `bun create tauri-app@latest`
