### ISSUE TITLE
[bug] a tauri app create by `npm create tauri-app` doesn't render properly

### ISSUE THREAD

**Issue by zw201913** [tauri-apps/create-tauri-app#87]
<img width="549" alt="image" src="https://user-images.githubusercontent.com/16849315/180133181-429ef6b5-3ea5-441c-b72c-fcae3825d0c1.png">
Then I start the project through the command about `npm run tauri dev`, but it gives an error when rendering。
<img width="800" alt="image" src="https://user-images.githubusercontent.com/16849315/180133902-39f7bfbd-0294-4b1b-9d51-a199e1ce3e6e.png">
Below is info of `npm run tauri info`:
<img width="380" alt="image" src="https://user-images.githubusercontent.com/16849315/180134132-f8c1d14c-bc8d-4436-8fe6-110462c993b0.png">
<img width="247" alt="image" src="https://user-images.githubusercontent.com/16849315/180134285-250df6f7-66bf-4427-8aa3-6ca777415fe9.png">
Below is struct of the project:
<img width="307" alt="image" src="https://user-images.githubusercontent.com/16849315/180134475-d1029953-1906-46b8-82d7-22e2406fe81b.png">
please tell me how to solve this problem? 
thx

**Comment by amrbashir** [comment]
Can you get a trace where this syntax error happens?

**Comment by zw201913** [comment]
I followed the documentation step by step, I guess the problem is on TypeScript, but I don't know TypeScript, so I can't locate the specific problem.

**Comment by amrbashir** [comment]
can you just expand the error in the console and copy it here.

**Comment by zw201913** [comment]
<img width="800" alt="image" src="https://user-images.githubusercontent.com/16849315/180980565-8db707f5-6d63-409c-93c9-98a09bc8f72e.png">

**Comment by amrbashir** [comment]
can you try opening the same vite project in safari?

**Comment by zw201913** [comment]
it is ok in chrome:
<img width="1211" alt="image" src="https://user-images.githubusercontent.com/16849315/181007749-16f1993f-5ce3-4df2-bab6-18732538da02.png">

**Comment by zw201913** [comment]
it is not ok in safari
<img width="1224" alt="image" src="https://user-images.githubusercontent.com/16849315/181008275-f96fd4ef-4191-4874-868f-84def821a4f7.png">

**Comment by zw201913** [comment]
the safari‘s version is 13.0.3 (13608.3.10.10.1)

**Comment by amrbashir** [comment]
Nothing we can do about it. Please open an issue at vite repo.
