### ISSUE TITLE
Remove or replace `svelte` template

### ISSUE THREAD

**Issue by HarryAllen1** [tauri-apps/create-tauri-app#88]
The [svelte template repo](https://github.com/sveltejs/template) says that the template is archived, and that either the vite-svelte template or svelte kit should be used.

A solution would be to use create-svelte@next package, although svelte-kit is still beta software.

**Comment by amrbashir** [comment]
see https://github.com/tauri-apps/create-tauri-app/pull/80#issuecomment-1178953574
